### ISSUE TITLE
Arbitrary Shells?

### ISSUE THREAD

**Issue by mknecht** [timofurrer/try#5]
Any reason not to allow arbitrary shells, instead of the ipython on/off switch? Personally, I'm using iptpython (a mix between [ptpython](https://github.com/jonathanslenders/ptpython) and ipython). Would be lovely to be able to say:

    try requests --shell ipython
    try requests --shell iptpython

or whatever shell someone is using.

Awesome project btw. :)

**Comment by timofurrer** [comment]
I was thinking about that too! Are you talking about `ptipython`? If not .. from where can I get it?

The question is how we make sure the shell is installed in the created virtualenv. For `ipython` and `ptpython` it's not a problem (we can just pip-install those). But it's a problem with `ptipython` because it only runs if `ipython` and `ptpython` are installed. 

I don't really want to hardcode this dependency. The easiest thing I could think of right now is to publish a package on PyPI called `ptipython` which acts as a metapackage to install `ipython` and `ptpython` which I'm not really a fan of ;) 

Any ideas?

**Comment by timofurrer** [comment]
I've implemented a `--shell` option to specify an arbitrary shell to launch. However, this does not solve the issue with `ptipython`. Do you have thoughts about it?

It's released with version `0.1.6`!

**Comment by timofurrer** [comment]
I just uploaded the following metapackage to PyPI: https://pypi.python.org/pypi/ptipython

This should solve the issue for now. I would be more than happy to remove this package as soon as we've got a better solution.

**Comment by mknecht** [comment]
Sorry burried in work … woah @timofurrer you're too fast. :)

Yes, I meant ptipython (without tab-completion my spelling's worthless)

And, honestly, I'd have thought that it's my fault for specifying a shell I don't have. This is awesome, though. Upgraded, thank you! :)
